import {ContentType, IContent} from '@/lib/types/content';
import {Difficulty} from '@/lib/types/sentence';
import {TokenType} from '@/lib/types/token';
import {
	ArticleType,
	ConjunctionFunction,
	ConjunctionType,
	DeterminerType,
	PartOfSpeech,
	PrepositionType,
	PronounCase,
	PronounType,
	VerbClass,
	VerbMood,
	VerbRegularity,
	VerbTense,
	VerbVoice,
} from '@/lib/types/partsOfSpeech';
import {
	GrammaticalGender,
	GrammaticalNumber,
	GrammaticalPerson,
} from '@/lib/types/grammar';

export const contentEntryDTMFBadBunny: IContent = {
	contentType: ContentType.SONG,
	contentId: 'song-dtmf-bad-bunny',
	title: 'DtMF',
	content: `Otro sunset bonito que veo en San Juan. Disfrutando de todas esas cosas que extrañan los que se van.`,
	sentencesIds: [
		'sentence-1-dtmf-bad-bunny',
		'sentence-2-dtmf-bad-bunny',
		'sentence-3-dtmf-bad-bunny',
	],
	language: {
		main: 'spanish',
		variant: ['puerto rico'],
	},
	contributors: {
		main: 'Bad Bunny',
	},
	source: 'https://www.youtube.com/watch?v=v9T_MGfzq7I&ab_channel=BadBunny',
	genre: ['reggaeton', 'latin trap'],
	createdAt: 1742454396457,
	updatedAt: 1742454396457,
	processedSentences: [
		{
			content: 'otro sunset bonito que veo en san juan.',
			sentenceId: 'sentence-1-dtmf-bad-bunny',
			tokenIds: [
				'token-otro',
				'token-sunset',
				'token-bonito',
				'token-que',
				'token-veo',
				'token-en',
				'token-san',
				'token-juan',
				'token-.',
			],
			translations: {
				english: {
					contextual: 'Another beautiful sunset I see in San Juan.',
					literal: 'Another beautiful sunset that I see in San Juan.',
				},
			},
			processedTokens: [
				{
					tokenId: 'token-otro',
					content: 'otro',
					tokenType: TokenType.Word,
					normalizedToken: 'otro',
					isSlang: false,
					isCognate: false,
					isFalseCognate: false,
					lastUpdated: 1742454396454,
					senses: [
						{
							partOfSpeech: PartOfSpeech.Adjective,
							senseId: 'sense-adjective-otro',
							tokenId: 'token-otro',
							translations: {
								english: ['other', 'another'],
							},
							lastUpdated: 1742453827556,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Adjective,
								gender: GrammaticalGender.Masculine,
								number: GrammaticalNumber.Singular,
							},
						},
						{
							partOfSpeech: PartOfSpeech.Pronoun,
							senseId: 'sense-pronoun-otro',
							tokenId: 'token-otro',
							translations: {
								english: ['another', 'other'],
							},
							lastUpdated: 1742453827556,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Pronoun,
								pronounType: PronounType.Indefinite,
								gender: GrammaticalGender.Masculine,
								number: GrammaticalNumber.Singular,
							},
						},
					],
				},
				{
					tokenId: 'token-sunset',
					content: 'sunset',
					tokenType: TokenType.Word,
					normalizedToken: 'sunset',
					isSlang: false,
					isCognate: true,
					isFalseCognate: false,
					lastUpdated: 1742454305918,
					senses: [
						{
							partOfSpeech: PartOfSpeech.Noun,
							senseId: 'sense-noun-sunset',
							tokenId: 'token-sunset',
							translations: {
								english: ['sunset'],
							},
							lastUpdated: 1742453827556,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Noun,
								gender: GrammaticalGender.Masculine,
								number: GrammaticalNumber.Singular,
							},
						},
					],
				},
				{
					tokenId: 'token-bonito',
					content: 'bonito',
					tokenType: TokenType.Word,
					normalizedToken: 'bonito',
					isSlang: false,
					isCognate: false,
					isFalseCognate: false,
					lastUpdated: 1742454324917,
					senses: [
						{
							partOfSpeech: PartOfSpeech.Adjective,
							senseId: 'sense-adjective-bonito',
							tokenId: 'token-bonito',
							translations: {
								english: ['pretty', 'beautiful', 'nice'],
							},
							lastUpdated: 1742453827556,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Adjective,
								gender: GrammaticalGender.Masculine,
								number: GrammaticalNumber.Singular,
							},
						},
					],
				},
				{
					tokenId: 'token-que',
					content: 'que',
					tokenType: TokenType.Word,
					normalizedToken: 'que',
					isSlang: false,
					isCognate: false,
					isFalseCognate: false,
					lastUpdated: 1739854154593,
					senses: [
						{
							partOfSpeech: PartOfSpeech.Conjunction,
							senseId: 'sense-conjunction-que',
							tokenId: 'token-que',
							translations: {
								english: ['that', 'than', 'since', 'as'],
							},
							lastUpdated: 1739853316748,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Conjunction,
								conjunctionType: ConjunctionType.Subordinating,
								conjunctionFunction: ConjunctionFunction.Causal,
							},
						},
						{
							partOfSpeech: PartOfSpeech.Pronoun,
							senseId: 'sense-pronoun-que',
							tokenId: 'token-que',
							translations: {
								english: ['who', 'whom', 'which', 'that'],
							},
							lastUpdated: 1739853316748,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Pronoun,
								pronounType: PronounType.Relative,
							},
						},
					],
				},
				{
					tokenId: 'token-veo',
					content: 'veo',
					tokenType: TokenType.Word,
					normalizedToken: 'veo',
					isSlang: false,
					isCognate: false,
					isFalseCognate: false,
					lastUpdated: 1742454232182,
					senses: [
						{
							partOfSpeech: PartOfSpeech.Verb,
							senseId: 'sense-verb-veo',
							tokenId: 'token-veo',
							translations: {
								english: ['I see'],
							},
							lastUpdated: 1742453827556,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Verb,
								tense: [VerbTense.Present],
								mood: VerbMood.Indicative,
								person: [GrammaticalPerson.FirstSingular],
								number: GrammaticalNumber.Singular,
								isRegular: false,
								infinitive: 'ver',
								voice: VerbVoice.Active,
								verbClass: VerbClass.Transitive,
								gerund: false,
								pastParticiple: false,
								verbRegularity: VerbRegularity.IrregularAll,
								isReflexive: false,
							},
						},
					],
				},
				{
					tokenId: 'token-en',
					content: 'en',
					tokenType: TokenType.Word,
					normalizedToken: 'en',
					isSlang: false,
					isCognate: false,
					isFalseCognate: false,
					lastUpdated: 1739854097676,
					senses: [
						{
							partOfSpeech: PartOfSpeech.Preposition,
							senseId: 'sense-preposition-en',
							tokenId: 'token-en',
							translations: {
								english: ['in', 'on', 'at'],
							},
							lastUpdated: 1739853316748,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Preposition,
								prepositionType: PrepositionType.Simple,
							},
						},
					],
				},
				{
					tokenId: 'token-san',
					content: 'san',
					tokenType: TokenType.Word,
					normalizedToken: 'san',
					isSlang: false,
					isCognate: false,
					isFalseCognate: false,
					lastUpdated: 1742454305918,
					senses: [
						{
							partOfSpeech: PartOfSpeech.Noun,
							senseId: 'sense-noun-san',
							tokenId: 'token-san',
							translations: {
								english: ['saint'],
							},
							lastUpdated: 1742453827556,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Noun,
								gender: GrammaticalGender.Masculine,
								number: GrammaticalNumber.Singular,
								isProperNoun: true,
							},
						},
					],
				},
				{
					tokenId: 'token-juan',
					content: 'juan',
					tokenType: TokenType.Word,
					normalizedToken: 'juan',
					isSlang: false,
					isCognate: false,
					isFalseCognate: false,
					lastUpdated: 1742454305918,
					senses: [
						{
							partOfSpeech: PartOfSpeech.Noun,
							senseId: 'sense-noun-juan',
							tokenId: 'token-juan',
							translations: {
								english: ['John'],
							},
							lastUpdated: 1742453827556,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Noun,
								gender: GrammaticalGender.Masculine,
								number: GrammaticalNumber.Singular,
								isProperNoun: true,
							},
						},
					],
				},
				{
					tokenId: 'token-.',
					content: '.',
					tokenType: TokenType.PunctuationSign,
				},
			],
		},
		{
			content: 'disfrutando de todas esas cosas que extrañan los que se van.',
			sentenceId: 'sentence-2-dtmf-bad-bunny',
			tokenIds: [
				'token-disfrutando',
				'token-de',
				'token-todas',
				'token-esas',
				'token-cosas',
				'token-que',
				'token-extrañan',
				'token-los',
				'token-que',
				'token-se',
				'token-van',
				'token-.',
			],
			translations: {
				english: {
					contextual: 'Enjoying all those things that those who leave miss.',
					literal: 'Enjoying of all those things that miss those that leave.',
				},
			},
			learningInsights: {
				insight:
					"The phrase 'los que se van' is a common way to refer to 'those who leave' or 'emigrants'. The verb 'extrañar' is used to express missing something or someone.",
				difficulty: Difficulty.INTERMEDIATE,
			},
			processedTokens: [
				{
					tokenId: 'token-disfrutando',
					content: 'disfrutando',
					tokenType: TokenType.Word,
					normalizedToken: 'disfrutando',
					isSlang: false,
					isCognate: false,
					isFalseCognate: false,
					lastUpdated: 1742454232182,
					senses: [
						{
							partOfSpeech: PartOfSpeech.Verb,
							senseId: 'sense-verb-disfrutando',
							tokenId: 'token-disfrutando',
							translations: {
								english: ['enjoying'],
							},
							lastUpdated: 1742453827556,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Verb,
								tense: [],
								mood: VerbMood.Gerund,
								person: [],
								number: '',
								isRegular: true,
								infinitive: 'disfrutar',
								voice: VerbVoice.Active,
								verbClass: VerbClass.Transitive,
								gerund: true,
								pastParticiple: false,
								verbRegularity: VerbRegularity.Regular,
								isReflexive: false,
							},
						},
					],
				},
				{
					tokenId: 'token-de',
					content: 'de',
					tokenType: TokenType.Word,
					normalizedToken: 'de',
					isSlang: false,
					isCognate: false,
					isFalseCognate: false,
					lastUpdated: 1739854097676,
					senses: [
						{
							partOfSpeech: PartOfSpeech.Preposition,
							senseId: 'sense-preposition-de',
							tokenId: 'token-de',
							translations: {
								english: ['of', 'from', 'in', 'on', 'with', 'by'],
							},
							lastUpdated: 1739853316748,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Preposition,
								prepositionType: PrepositionType.Simple,
							},
						},
					],
				},
				{
					tokenId: 'token-todas',
					content: 'todas',
					tokenType: TokenType.Word,
					normalizedToken: 'todas',
					isSlang: false,
					isCognate: false,
					isFalseCognate: false,
					lastUpdated: 1742454396454,
					senses: [
						{
							partOfSpeech: PartOfSpeech.Determiner,
							senseId: 'sense-determiner-todas',
							tokenId: 'token-todas',
							translations: {
								english: ['all', 'every'],
							},
							lastUpdated: 1742453827556,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Determiner,
								determinerType: DeterminerType.Indefinite,
								gender: GrammaticalGender.Feminine,
								number: GrammaticalNumber.Plural,
							},
						},
						{
							partOfSpeech: PartOfSpeech.Pronoun,
							senseId: 'sense-pronoun-todas',
							tokenId: 'token-todas',
							translations: {
								english: ['all', 'everyone'],
							},
							lastUpdated: 1742453827556,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Pronoun,
								pronounType: PronounType.Indefinite,
								person: GrammaticalPerson.ThirdPlural,
								gender: GrammaticalGender.Feminine,
								number: GrammaticalNumber.Plural,
							},
						},
					],
				},
				{
					tokenId: 'token-esas',
					content: 'esas',
					tokenType: TokenType.Word,
					normalizedToken: 'esas',
					isSlang: false,
					isCognate: false,
					isFalseCognate: false,
					lastUpdated: 1742454396454,
					senses: [
						{
							partOfSpeech: PartOfSpeech.Determiner,
							senseId: 'sense-determiner-esas',
							tokenId: 'token-esas',
							translations: {
								english: ['those'],
							},
							lastUpdated: 1742453827556,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Determiner,
								determinerType: DeterminerType.Demonstrative,
								gender: GrammaticalGender.Feminine,
								number: GrammaticalNumber.Plural,
							},
						},
						{
							partOfSpeech: PartOfSpeech.Pronoun,
							senseId: 'sense-pronoun-esas',
							tokenId: 'token-esas',
							translations: {
								english: ['those'],
							},
							lastUpdated: 1742453827556,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Pronoun,
								pronounType: PronounType.Demonstrative,
								gender: GrammaticalGender.Feminine,
								number: GrammaticalNumber.Plural,
								person: GrammaticalPerson.ThirdPlural,
							},
						},
					],
				},
				{
					tokenId: 'token-cosas',
					content: 'cosas',
					tokenType: TokenType.Word,
					normalizedToken: 'cosas',
					isSlang: false,
					isCognate: false,
					isFalseCognate: false,
					lastUpdated: 1742454305918,
					senses: [
						{
							partOfSpeech: PartOfSpeech.Noun,
							senseId: 'sense-noun-cosas',
							tokenId: 'token-cosas',
							translations: {
								english: ['things'],
							},
							lastUpdated: 1742453827556,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Noun,
								gender: GrammaticalGender.Feminine,
								number: GrammaticalNumber.Plural,
							},
						},
					],
				},
				{
					tokenId: 'token-que',
					content: 'que',
					tokenType: TokenType.Word,
					normalizedToken: 'que',
					isSlang: false,
					isCognate: false,
					isFalseCognate: false,
					lastUpdated: 1739854154593,
					senses: [
						{
							partOfSpeech: PartOfSpeech.Conjunction,
							senseId: 'sense-conjunction-que',
							tokenId: 'token-que',
							translations: {
								english: ['that', 'than', 'since', 'as'],
							},
							lastUpdated: 1739853316748,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Conjunction,
								conjunctionType: ConjunctionType.Subordinating,
								conjunctionFunction: ConjunctionFunction.Causal,
							},
						},
						{
							partOfSpeech: PartOfSpeech.Pronoun,
							senseId: 'sense-pronoun-que',
							tokenId: 'token-que',
							translations: {
								english: ['who', 'whom', 'which', 'that'],
							},
							lastUpdated: 1739853316748,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Pronoun,
								pronounType: PronounType.Relative,
							},
						},
					],
				},
				{
					tokenId: 'token-extrañan',
					content: 'extrañan',
					tokenType: TokenType.Word,
					normalizedToken: 'extrañan',
					isSlang: false,
					isCognate: false,
					isFalseCognate: false,
					lastUpdated: 1742454232182,
					senses: [
						{
							partOfSpeech: PartOfSpeech.Verb,
							senseId: 'sense-verb-extrañan',
							tokenId: 'token-extrañan',
							translations: {
								english: ['to miss', 'to long for'],
							},
							lastUpdated: 1742453827556,
							hasSpecialChar: true,
							grammaticalInfo: {
								type: PartOfSpeech.Verb,
								tense: [VerbTense.Present],
								mood: VerbMood.Indicative,
								person: [GrammaticalPerson.ThirdSingular],
								number: GrammaticalNumber.Plural,
								isRegular: true,
								infinitive: 'extrañar',
								voice: VerbVoice.Active,
								verbClass: VerbClass.Transitive,
								gerund: false,
								pastParticiple: false,
								verbRegularity: VerbRegularity.Regular,
								isReflexive: false,
							},
						},
					],
				},
				{
					tokenId: 'token-los',
					content: 'los',
					tokenType: TokenType.Word,
					normalizedToken: 'los',
					isSlang: false,
					isCognate: false,
					isFalseCognate: false,
					lastUpdated: 1742454396454,
					senses: [
						{
							partOfSpeech: PartOfSpeech.Article,
							senseId: 'sense-article-los',
							tokenId: 'token-los',
							translations: {
								english: ['the'],
							},
							lastUpdated: 1742453827556,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Article,
								articleType: ArticleType.DEFINITE,
								gender: GrammaticalGender.Masculine,
								number: GrammaticalNumber.Plural,
							},
						},
						{
							partOfSpeech: PartOfSpeech.Pronoun,
							senseId: 'sense-pronoun-los',
							tokenId: 'token-los',
							translations: {
								english: ['them'],
							},
							lastUpdated: 1742453827556,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Pronoun,
								pronounType: PronounType.Personal,
								person: GrammaticalPerson.ThirdPlural,
								gender: GrammaticalGender.Masculine,
								number: GrammaticalNumber.Plural,
								case: PronounCase.Accusative,
								isReflexive: false,
								isReciprocal: false,
							},
						},
					],
				},
				{
					tokenId: 'token-que',
					content: 'que',
					tokenType: TokenType.Word,
					normalizedToken: 'que',
					isSlang: false,
					isCognate: false,
					isFalseCognate: false,
					lastUpdated: 1739854154593,
					senses: [
						{
							partOfSpeech: PartOfSpeech.Conjunction,
							senseId: 'sense-conjunction-que',
							tokenId: 'token-que',
							translations: {
								english: ['that', 'than', 'since', 'as'],
							},
							lastUpdated: 1739853316748,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Conjunction,
								conjunctionType: ConjunctionType.Subordinating,
								conjunctionFunction: ConjunctionFunction.Causal,
							},
						},
						{
							partOfSpeech: PartOfSpeech.Pronoun,
							senseId: 'sense-pronoun-que',
							tokenId: 'token-que',
							translations: {
								english: ['who', 'whom', 'which', 'that'],
							},
							lastUpdated: 1739853316748,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Pronoun,
								pronounType: PronounType.Relative,
							},
						},
					],
				},
				{
					tokenId: 'token-se',
					content: 'se',
					tokenType: TokenType.Word,
					normalizedToken: 'se',
					isSlang: false,
					isCognate: false,
					isFalseCognate: false,
					lastUpdated: 1739853316748,
					senses: [
						{
							partOfSpeech: PartOfSpeech.Pronoun,
							senseId: 'sense-pronoun-se',
							tokenId: 'token-se',
							translations: {
								english: [
									'himself',
									'herself',
									'itself',
									'themselves',
									'yourself',
									'yourselves',
									'each other',
									'one another',
								],
							},
							lastUpdated: 1739853316748,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Pronoun,
								pronounType: PronounType.Personal,
								person: [
									GrammaticalPerson.ThirdSingular,
									GrammaticalPerson.ThirdSingular,
								],
								case: PronounCase.Accusative,
								isReflexive: true,
								isReciprocal: false,
							},
						},
						{
							partOfSpeech: PartOfSpeech.Pronoun,
							senseId: 'sense-pronoun-se',
							tokenId: 'token-se',
							translations: {
								english: ['passive reflexive', 'impersonal reflexive'],
							},
							lastUpdated: 1739853316748,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Pronoun,
								pronounType: PronounType.Personal,
								person: [
									GrammaticalPerson.ThirdSingular,
									GrammaticalPerson.ThirdSingular,
								],
								case: PronounCase.Accusative,
								isReflexive: true,
								isReciprocal: false,
							},
						},
					],
				},
				{
					tokenId: 'token-van',
					content: 'van',
					tokenType: TokenType.Word,
					normalizedToken: 'van',
					isSlang: false,
					isCognate: false,
					isFalseCognate: false,
					lastUpdated: 1739853316748,
					senses: [
						{
							partOfSpeech: PartOfSpeech.Verb,
							senseId: 'sense-verb-van',
							tokenId: 'token-van',
							translations: {
								english: ['they go'],
							},
							lastUpdated: 1739853316748,
							hasSpecialChar: false,
							grammaticalInfo: {
								type: PartOfSpeech.Verb,
								tense: [VerbTense.Present],
								mood: VerbMood.Indicative,
								person: [GrammaticalPerson.ThirdSingular],
								number: GrammaticalNumber.Plural,
								isRegular: false,
								infinitive: 'ir',
								voice: VerbVoice.Active,
								verbClass: VerbClass.Intransitive,
								gerund: false,
								pastParticiple: false,
								verbRegularity: VerbRegularity.IrregularAll,
								isReflexive: false,
							},
						},
					],
				},
				{
					tokenId: 'token-.',
					content: '.',
					tokenType: TokenType.PunctuationSign,
				},
			],
		},
	],
};
